### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified.

### ISSUE THREAD

**Issue by abdullahicyc** [sudoliyang/CodeSchool-Downloader#2]
When i run "python parsing_courses_to_json.py" , it crashes and this is the traceback error.

`Traceback (most recent call last):
  File "C:\Users\cyc\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Users\cyc\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\cyc\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parsing_courses_to_json.py", line 13, in <module>
    browser = webdriver.Firefox()
  File "C:\Users\cyc\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 144, in __init__
    self.service.start()
  File "C:\Users\cyc\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.`

**Comment by Donly-Wilson** [comment]
Am going to guess that you have Selenium installed.If not get it here https://pypi.python.org/pypi/selenium/3.7.0

The main problem here is with "GECKODRIVER" 
   [ N.B you dont need to run the geckodriver.exe file]

 1) First download it for here  https://github.com/mozilla/geckodriver/releases   (Make sure is for the right system(Linux or Win) and right bit(64x or 32x)

  2) Second just follow this video on how to select the path   https://youtu.be/KNzGtHI_60o
Should solve proplem

**Comment by abdullahicyc** [comment]
@Wizy17 @sudoliyang Show me parsing_courses_to_json.py file sample

**Comment by Donly-Wilson** [comment]
Is the Error something like this:

Signed !
<class 'str'>
Traceback (most recent call last):
  File "parsing_courses_to_json.py", line 125, in <module>
    print (str)(index) + "  " + "https://www.codeschool.com" + Link + '/videos'
TypeError: 'NoneType' object is not callable

If this is the error then that's where am also stuck.

Screencasting works fine for me but there is no way to end until it completes all the vids which looks like a ton of hours
